version: "3"

services:
  postgres:
    image: postgres:14
    container_name: java_postgres
    environment:
      POSTGRES_USER: bankomat
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bankomat
    healthcheck:
     test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1" ]
     interval: 5s
     timeout: 5s
     retries: 20


  app:
   build: ./
   container_name: java_app
   ports:
    - "8080:8080"
   environment:
    DB_HOST: postgres
    SPRING_DATASOURCE_USERNAME: bankomat
    SPRING_DATASOURCE_PASSWORD: 123456

   depends_on:
    postgres:
      condition: service_healthy


